create table discount_campaign (
    campaign_id bigint generated by default as identity primary key,
    name text not null,
    description text,
    discount_percent numeric(5, 2) not null,
    starts_at timestamptz not null,
    ends_at timestamptz not null,
    enabled boolean not null default true,
    created_by integer not null references "user" (user_id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint discount_campaign_percent_check
        check (discount_percent > 0 and discount_percent <= 100),
    constraint discount_campaign_time_check
        check (ends_at > starts_at)
);

create table discount_campaign_book (
    campaign_id bigint not null references discount_campaign (campaign_id) on delete cascade,
    book_id integer not null references book (book_id),
    primary key (campaign_id, book_id)
);

create index discount_campaign_book_book_idx
    on discount_campaign_book (book_id, campaign_id);

create index discount_campaign_active_window_idx
    on discount_campaign (starts_at, ends_at, discount_percent desc)
    where enabled = true;
